ocfs2-test: fix build error
libocfs2 depends on libaio, add the reference to libaio where libocfs2
exist to fix the following build error.

gcc -O2 -Wall -g  -o inline-data inline-data.o inline-data-utils.o -locfs2
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libocfs2.a(unix_io.o): In function `unix_vec_read_blocks':
(.text+0x874): undefined reference to `io_queue_init'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libocfs2.a(unix_io.o): In function `unix_vec_read_blocks':
(.text+0x909): undefined reference to `io_submit'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libocfs2.a(unix_io.o): In function `unix_vec_read_blocks':
(.text+0x949): undefined reference to `io_queue_release'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../lib64/libocfs2.a(unix_io.o): In function `unix_vec_read_blocks':
(.text+0x988): undefined reference to `io_getevents'
collect2: ld returned 1 exit status

Signed-off-by: Junxiao Bi <junxiao.bi@oracle.com>